### ISSUE TITLE
Issue with path.normalize

### ISSUE THREAD

**Issue by RogerHardiman** [hokiedsp/node-kiss-ffmpeg#4]
### Version information

* fluent-ffmpeg version: - Kiss-ffmpeg version 0.30.0
* ffmpeg version: 4.3.1
* OS: Linux

Input is a RTSP URL

kiss-ffmpeg has this code 
```
      args.push("-i");
      args.push(path.normalize(url));
```

This replaces rtsp://hostname/path
with rtsp:/hostname/path

So the source code drops one slash after rtsp://

### Expected results
Pass the correct URL to ffmpeg

### Observed results
ffmpeg seems to work, but from the logs I can see we are passing a bad URL to ffmpeg

No output results - this a found with a Code Review.

**Comment by hokiedsp** [comment]
@RogerHardiman - Thanks for reporting the issue. I can certainly see that line would cause an issue.

I'm a bit busy right now with other projects and if you'd like to address it with a PR, that would speed up the fix. I will try to follow through asap.

**Comment by RogerHardiman** [comment]
Hi there.
I can do a PR, but I'm not sure what the best way to implement it is.
So any pointers would be good.

So I could look for strings that start http:// or rtsp:// and then not use path.normalise  for them.
I wonder if there is a better way to spot URLs rather than file paths.

**Comment by hokiedsp** [comment]
Good point. My gut feeling is to convert it to a URL Object (file:// for local files) if ffmpeg allows it so it’ll be More or less future proof

**Comment by hokiedsp** [comment]
@RogerHardiman - OK, I looked at the code tonight and decided to just drop the auto-normalization support. There are simply too many supported protocols for it to be useful. I've published the update with a minor version bump. Hopefully, this resolves the issue with your project. Thanks!

**Comment by RogerHardiman** [comment]
Hi there
That sounds like a good idea to drop the normalise.
Thanks for the version bump.

Just for your information, I am using the library to spin up ffmpeg, connect to a RTSP stream, wait for 1 frame of video and extract the image, scale it and output a JPEG.
It is a re-write of something I do in the Open Source RPOS project (a Raspberry Pi ONVIF Server)

**Comment by hokiedsp** [comment]
NP, and thanks for letting me know of your use. I only use FFmpeg myself to process local files, so it’s nice to get feedback for using it for stream processing. If you encounter anything else (or any feature request) pls don’t hesitate to start another case! Sent from Mail for Windows 10 From: Roger HardimanSent: Wednesday, March 10, 2021 6:49 AMTo: hokiedsp/node-kiss-ffmpegCc: Kesh Ikuma; CommentSubject: Re: [hokiedsp/node-kiss-ffmpeg] Issue with path.normalize (#4) Hi thereThat sounds like a good idea to drop the normalise.Thanks for the version bump.Just for your information, I am using the library to spin up ffmpeg, connect to a RTSP stream, wait for 1 frame of video and extract the image, scale it and output a JPEG.It is a re-write of something I do in the Open Source RPOS project (a Raspberry Pi ONVIF Server)—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.
